/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panel;

import gui.panel.paintWorker.IWorkerInterface;
import gui.panel.paintWorker.WorkerShapesVideo;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nick
 */
public class jPanelVideoPlayer extends javax.swing.JPanel {

    /**
     * Creates new form jPanelVideoShapes
     */
    private Image src;

    public jPanelVideoPlayer(IWorkerInterface worker) {
        initComponents();
        initWorker(worker);

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (src != null) {
            g.drawImage(src, 0, 0, this);
            g.dispose();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Video area"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame jf = new JFrame();
//                jf.setDefaultCloseOperation();
                controller.Controller.getInstance().setMedia("cam");
                controller.Controller.getInstance().playMedia();
                WorkerShapesVideo w = new WorkerShapesVideo();
//                WorkerNormalVideo w = new WorkerNormalVideo();
                jPanelVideoPlayer jp = new jPanelVideoPlayer(w);
                jf.getContentPane().add(jp, BorderLayout.CENTER);
                jf.setSize(1024, 768);
                jf.setVisible(true);
                System.out.println("podigao");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void setSrc(Image src) {
        this.src = src;
    }

    private void initWorker(IWorkerInterface worker) {
        IWorkerInterface w = worker;
        w.setTopPanel(this);
        w.execute();
    }
}
